# Generated by Django 2.0.2 on 2018-02-19 12:53

from django.db import migrations, models
import django.db.models.deletion
import yamlfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('tarefas_por_trabalho', models.IntegerField()),
                ('descricao', models.TextField(default='', help_text='Descrição desta campanha. Você pode inserir código HTML aqui.')),
                ('ativa', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('estrutura', yamlfield.fields.YAMLField(help_text='\n<pre>nome: "Nome do Formulário"\ncampos:\n    - escolha:\n        nome: "nomeprogramatico"\n        label: "Label do Campo"\n        cardinalidade: ("multipla"|"unica")\n        tipo: ("boolean"|"int"|"string")\n        opcoes: \n            - "label1"\n            - "label2"\n            - "label3"\n        valores:\n            - "val1"\n            - "val2"\n            - "val3"\n    - check:\n        nome: "outronomeprogramatico"\n        label: "Outro Label do Campo"\n        default: false</pre>\n    ')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=255)),
                ('nome_campo', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField()),
                ('texto_inteligencia', models.TextField()),
                ('classificacao', models.CharField(max_length=500)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labeler.Campanha')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=255)),
                ('tarefas', models.ManyToManyField(to='labeler.Tarefa')),
            ],
        ),
        migrations.AddField(
            model_name='resposta',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labeler.Tarefa'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='labeler.Formulario'),
        ),
    ]
