# Generated by Django 2.0.2 on 2018-03-12 13:23

from django.db import migrations, models
import yamlfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='situacao',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='descricao',
            field=models.TextField(default='', help_text='Descrição desta campanha. Você pode inserir códigos HTML.'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='estrutura',
            field=yamlfield.fields.YAMLField(help_text='\n<pre>nome: "Nome do Formulário"\ncampos:\n    - escolha:\n        nome: "nomeprogramatico"\n        label: "Label do Campo"\n        cardinalidade: ("multipla"|"unica")\n        tipo: ("boolean"|"int"|"string")\n        opcoes:\n            - "label1"\n            - "label2"\n            - "label3"\n        valores:\n            - "val1"\n            - "val2"\n            - "val3"\n    - check:\n        nome: "outronomeprogramatico"\n        label: "Outro Label do Campo"\n        default: false</pre>\n    '),
        ),
    ]
