# Generated by Django 2.0.2 on 2018-03-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0002_auto_20180312_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='trabalho',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='labeler.Trabalho'),
            preserve_default=False,
        ),
    ]
