# Generated by Django 2.0.2 on 2018-06-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0003_resposta_trabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='numero_documento',
            field=models.CharField(default='', max_length=255),
        ),
    ]
