# Generated by Django 2.0.2 on 2018-04-06 15:12

from django.db import migrations, models
import django.db.models.deletion


def descobre_campanha(apps, schema_editor):
    Trabalho = apps.get_model('labeler', 'Trabalho')

    for trabalho in Trabalho.objects.all():
        campanha = trabalho.tarefas.first().campanha
        trabalho.campanha = campanha
        trabalho.save()


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0003_resposta_trabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='campanha',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='labeler.Campanha'),
            preserve_default=False,
        ),
	migrations.RunPython(descobre_campanha),
    ]
