# Generated by Django 2.0.2 on 2019-01-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseFiltro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=32)),
                ('conteudo', models.TextField()),
                ('filtro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filtro.ClasseFiltro')),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('arquivo_documentos', models.FileField(blank=True, null=True, upload_to='')),
                ('situacao', models.CharField(choices=[(1, 'Em Criação'), (2, 'Baixando Documentos'), (3, 'Executando Filtros'), (4, 'Documentos Classificados'), (5, 'Compactando'), (6, 'Download Disponível')], max_length=1)),
                ('saida', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFiltro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termos', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[(1, 'Expressão Principal'), (2, 'Expressão Reforço'), (3, 'Termos de Exclusão'), (4, 'Termos de Invalidação'), (5, 'Termos de Reforço')], max_length=1)),
                ('classe_filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtro.ClasseFiltro')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMovimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nome_tj', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='filtro',
            name='tipos_movimento',
            field=models.ManyToManyField(to='filtro.TipoMovimento'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_movimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtro.TipoMovimento'),
        ),
        migrations.AddField(
            model_name='classefiltro',
            name='filtro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtro.Filtro'),
        ),
    ]
