# Generated by Django 2.0.2 on 2019-01-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtro',
            name='responsavel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='situacao',
            field=models.CharField(choices=[('1', 'Em Criação'), ('2', 'Baixando Documentos'), ('3', 'Executando Filtros'), ('4', 'Documentos Classificados'), ('5', 'Compactando'), ('6', 'Download Disponível')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='itemfiltro',
            name='tipo',
            field=models.CharField(choices=[('1', 'Expressão Principal'), ('2', 'Expressão Reforço'), ('3', 'Termos de Exclusão'), ('4', 'Termos de Invalidação'), ('5', 'Termos de Reforço')], max_length=1),
        ),
    ]
