# Generated by Django 2.0.2 on 2019-01-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtro', '0002_auto_20190118_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classefiltro',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='classefiltro',
            name='ordem',
        ),
        migrations.AddField(
            model_name='classefiltro',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
