# Generated by Django 2.0.2 on 2019-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtro', '0003_auto_20190118_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfiltro',
            name='regex',
            field=models.BooleanField(default=False),
        ),
    ]
