# Generated by Django 2.0.2 on 2019-01-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtro', '0005_auto_20190123_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtro',
            name='percentual_atual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='situacao',
            field=models.CharField(choices=[('1', 'Em Criação'), ('2', 'Baixando Documentos'), ('3', 'Documentos Baixados'), ('4', 'Executando Filtros'), ('5', 'Documentos Classificados'), ('6', 'Compactando'), ('7', 'Download Disponível')], default='1', max_length=1),
        ),
    ]
