# Generated by Django 2.0.2 on 2019-04-15 18:56

from django.db import migrations, models
import filtro.storages


def forward_func_filtro(apps, schema_editor):
    Filtro = apps.get_model("filtro", "Filtro")
    db_alias = schema_editor.connection.alias
    Filtro.objects.using(db_alias).update(
        tipo_raspador='1'
    )


def reverse_func_filtro(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('filtro', '0006_auto_20190125_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtro',
            name='tipo_raspador',
            field=models.CharField(blank=True, choices=[('1', 'Tribunal de Justiça do Rio de Janeiro'), ('2', 'Arquivo Tabulado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='filtro',
            name='saida',
            field=models.FileField(blank=True, null=True, storage=filtro.storages.OverwriteStorage(), upload_to=''),
        ),
        migrations.RunPython(forward_func_filtro, reverse_func_filtro),
    ]
