# Generated by Django 2.0.2 on 2019-04-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtro', '0007_auto_20190415_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtro',
            name='tipos_movimento',
            field=models.ManyToManyField(blank=True, to='filtro.TipoMovimento'),
        ),
    ]
