# Generated by Django 2.0.2 on 2019-07-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtro', '0009_auto_20190416_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtro',
            name='saida_lda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
