# Generated by Django 2.0.2 on 2020-08-17 14:08

from django.conf import settings
from django.db import migrations

from filtro.models import TipoMovimento

SQL_INSERT_PETICAO_INICIAL = f"""
    INSERT INTO {TipoMovimento._meta.db_table} (nome, nome_tj)
    VALUES ('{settings.NOME_FILTRO_PETICAO_INICIAL}', 'peti[çc][ãa]o inicial');
    """

SQL_DELETE_PETICAO_INICIAL = f"""
    DELETE FROM {TipoMovimento._meta.db_table} WHERE nome='{settings.NOME_FILTRO_PETICAO_INICIAL}';
"""


class Migration(migrations.Migration):

    dependencies = [
        ('filtro', '0010_filtro_saida_lda'),
    ]

    operations = [
        migrations.RunSQL(SQL_INSERT_PETICAO_INICIAL, reverse_sql=SQL_DELETE_PETICAO_INICIAL),
    ]
