# Generated by Django 2.0.2 on 2019-12-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtro', '0010_filtro_saida_lda'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropriedadeDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtro.Documento')),
            ],
        ),
    ]
