# Generated by Django 2.0.2 on 2020-03-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filtro', '0010_filtro_saida_lda'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAcessoFiltro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtro.Filtro')),
            ],
        ),
    ]
