# Generated by Django 2.0.2 on 2020-08-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filtro', '0011_auto_20200817_1408'),
        ('filtro', '0011_usuarioacessofiltro'),
    ]

    operations = [
    ]
